name: Go

on:
  push:
#    branches: [ "develop" ]
#  pull_request:
#    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Unit Test
        run: |
          go test -v ./...
   
  # docker:
  #   name: docker-build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: mr-smithers-excellent/docker-build-push@v5
  #       name: Build & push Docker image
  #       with:
  #         image: ipehr-stats
  #         registry: ghcr.io
  #         githubOrg: bsn-si
  #         username: ${{ secrets.GHCR_USERNAME }}
  #         password: ${{ secrets.GHCR_TOKEN }}
